### ISSUE TITLE
DID Wallet Reopens Randomly

### ISSUE THREAD

**Issue by pjvargo43** [ArcBlock/did-wallet-sdk-android#8]
I have downloaded DID wallet onto my android phone which is a Samsung 8+ just a few days ago. While operating on my phone, DID wallet would interrupt my tasks by opening randomly. Sometimes reopening right after closing the app several times. To the point where its becoming a nuisance. Anyone might know of the issue? Is it on my end or a programming isssue.

**Comment by mave99a** [comment]
Thanks @pjvargo43 for reporting this issue.  would it be possible to have a screen recording to help us understand the issue better?

Pls. make sure don't share any private information in the video.

**Comment by PaperHS** [comment]
Hi , @pjvargo43 , have you ever open DID Wallet in your browser. (such as: click a button and pop a window to open app).
Have you closed this web page ?

**Comment by pjvargo43** [comment]
Thank you @mave99a & @PaperHS for getting back to me. Uusually photos would help in understanding the issue much better but in the case, it's the login/biometrics page which shows no errors. 

Ok, I did notice I attempted to login through Arcblock.io on Brave Browser but forgot the reason doing so. Attached are the opening page(s) for DID wallet. I guess I'll report back if it happens again like before. 
![20221217_195828](https://user-images.githubusercontent.com/59556028/208280768-436447ed-b8cf-4805-8c94-1b7f4bda9ca9.jpg)

**Comment by pjvargo43** [comment]
Sorry, my mistake.

**Comment by pjvargo43** [comment]
In the past 10 minutes, DID wallet has popped 4 times as soon as I opened Twitter and literally 6 times, wait....make that 7, nope 8 times while writing this message. Wait, 9,10,  11 , 12, 13, 14 times. How do you change the option to not close with comment....?

**Comment by pjvargo43** [comment]
OMG, its non stop. Like every 10 to 15 seconds it wants to open.

**Comment by mave99a** [comment]
Thank you for helping us repro the issue. To avoid the popping , probably you can try to manually stop the browser.

**Comment by pjvargo43** [comment]
Yeah, no worries. I'm glad I could help. Hiccups come and go. I'm sure this will be resolved on no time.

As for manually stopping the app on my Android phone, I've turned off all permissions, notifications and allowing the the app to run in the background....but again, the app popped up several times while writing this comment.

![Screenshot_20221217-215139_Settings](https://user-images.githubusercontent.com/59556028/208284292-a38f80af-2adf-49ea-931e-ae1dbe2b339a.jpg)
![Screenshot_20221217-215120_Settings](https://user-images.githubusercontent.com/59556028/208284296-09469d5b-924b-4028-a1fc-68ee6adae6fa.jpg)
![Screenshot_20221217-215026_Settings](https://user-images.githubusercontent.com/59556028/208284305-c63978fd-5f46-4793-b989-86abc66cc8eb.jpg)

**Comment by PaperHS** [comment]
> Yeah, no worries. I'm glad I could help. Hiccups come and go. I'm sure this will be resolved in no time.
> 
> As for manually stopping the app on my Android phone, I've turned off all permissions, notifications and allowing the the app to run in the background....but again, the app popped up several times while writing this comment.
> 
> ![Screenshot_20221217-215139_Settings](https://user-images.githubusercontent.com/59556028/208284292-a38f80af-2adf-49ea-931e-ae1dbe2b339a.jpg) ![Screenshot_20221217-215120_Settings](https://user-images.githubusercontent.com/59556028/208284296-09469d5b-924b-4028-a1fc-68ee6adae6fa.jpg) ![Screenshot_20221217-215026_Settings](https://user-images.githubusercontent.com/59556028/208284305-c63978fd-5f46-4793-b989-86abc66cc8eb.jpg)

@pjvargo43  Have you tried to close the tabs about arcblock.io(make sure close tab, not kill the broswer prosess), open twitter may restart chrome kernel. If it works, please noti me here, thanks!

**Comment by pjvargo43** [comment]
Yes, last night I made sure all the tabs were closed and that i restarted the browser but it was still acting up. As for this morning till now, it hasn't popped, even logging onto Brave, Twitter and so on. I think I stopped it from happening again. 🤞 I tried deleting the cache for the past 7 days to see if that was hanging on to the route cause. So far so good. 👍 I'll report back later today and if it hasn't come up, at all, I'll say we found it and it's been resolved.

**Comment by pjvargo43** [comment]
Well, not once did the wallet pop up out of the blue. I would call that a win. Thank you @mave99a and @PaperHS for helping me get through this. I hope we were able to learn something from this. 

🎄☃️❄🎄 Happy Holiday's ☃️🎄❄🎄

**Comment by PaperHS** [comment]
> Well, not once did the wallet pop up out of the blue. I would call that a win. Thank you @mave99a and @PaperHS for helping me get through this. I hope we were able to learn something from this.
> 
> 🎄☃️❄🎄 Happy Holiday's ☃️🎄❄🎄

I'm really happy for it works ! and thank you for reporting this issue! Happy holiday!
